name: oneos
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  flutter_screenutil: ^5.9.0
  get: ^4.6.6 # GetX package for state management, routing, and dependency injection
  pocketbase: ^0.23.0
  shared_preferences: ^2.2.2 # 用于持久化存储登录信息
  intl: ^0.20.2 # 用于日期格式化
  device_info_plus: ^10.1.0 # 用于获取设备信息
  fl_chart: ^0.68.0 # 用于图表展示
  qr_flutter: ^4.1.0 # 用于生成二维码
  flutter_svg: ^2.0.10+1 # 用于渲染SVG图标
  vibration: ^2.0.0 # 用于震动反馈
  connectivity_plus: ^6.0.5 # 用于网络连接状态检测
  network_info_plus: ^5.0.3 # 用于获取网络信息
  permission_handler: ^11.3.1 # 用于权限管理
  http: ^1.1.0 # 用于HTTP请求

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
